### ISSUE TITLE
add listeners

### ISSUE THREAD

**Issue by amir-arad** [shroudedcode/contro#13]
for using contro without game loops it might come in handy

**Comment by amir-arad** [comment]
on second thought that's exactly what this lib is not about. sorry :)

**Comment by shroudedcode** [comment]
@amir-arad No worries. I understand that the polling-based API isn't suitable in all cases but offering event listeners as well might over-complicate the API. I might have a go at designing an API that combines both approaches at some point but I can't promise anything.
