### ISSUE TITLE
Stick Error

### ISSUE THREAD

**Issue by ashikuri** [shroudedcode/contro#14]
Hello, whenever I do `gamepad.stick("left").query()` I get this error: Uncaught (in promise) TypeError: Cannot read property 'timestamp' of undefined

Why?

**Comment by shroudedcode** [comment]
I assume that's because you don't have a (standard mapping) gamepad connected and haven't specified a keyboard fallback using `or`. Can you post a screenshot of what you can see on the [HTML5 Gamepad Tester](https://html5gamepad.com/)?

**Comment by ashikuri** [comment]
![image](https://user-images.githubusercontent.com/53426441/79449534-ae7db880-7fe3-11ea-8523-44ce8f98a928.png)
if I have gamepad and it is connected but with tests I noticed that it's chrome that doesn't detect my joystick if I don't touch any of the buttons. If when loading the page I touch one of the buttons it will work, and for FireFox it's worse because even if I touch a button while the page is loading it tells me that `gamepad is undefined`.  🤔?

**Comment by shroudedcode** [comment]
> I noticed that it's chrome that doesn't detect my joystick if I don't touch any of the buttons

That's just how it is and I can't do anything against that. :confused:

What I can do, though, is make sure that `gamepad.stick("left").query()` doesn't throw an error when no gamepad has been detected yet. This way everything will work once the gamepad has been detected.

I've just released [version 2.1.4](https://github.com/shroudedcode/contro/releases/tag/v2.1.4) with this fix, so please give it a try.

**Comment by ashikuri** [comment]
thank you for solving the problem it works fine ^^

**Comment by shroudedcode** [comment]
No problem! :blush:
