### ISSUE TITLE
more?

### ISSUE THREAD

**Issue by hanako-eo** [shroudedcode/contro#19]
Hey it's possible to add detection of more gamepads?

**Comment by zardoy** [comment]
@shroudedcode hey how are you doing? I created a fork a long time ago and implemented everything I ever wanted with the best possible DX: https://github.com/zardoy/contro-max and my app https://mcraft.fun/ now [uses it](https://github.com/zardoy/prismarine-web-client/blob/85c0eb8c5b74359c39903f8a4bb0b221fb0756fd/src/controls.ts#L155)! Thank you for you so much for your initial inspiration
